config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about_us', to: "home#about"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :doctors, controllers: { registrations: 'doctors/registrations' }
  devise_for :users
  resources :categories, only: [:index, :show]
  resources :appointments, only: [:new, :create ]
  resources :users, only: [:profile] do
    get 'appointments', to: 'users#appointments', on: :member
  end
  resources :doctors, only: [:index, :show] do
    get 'recommendations', on: :member
    patch 'update_recommendation', on: :member
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  MAX_APPOINTMENT_COUNT = 10
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments, dependent: :destroy
  belongs_to :category, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true, uniqueness: true, format: { with: /\A\d{10}\z/, message: "should be a 10-digit number" }
end

app/controllers/doctors/confirmations_controller.rb
# frozen_string_literal: true

class Doctors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/doctors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Doctors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/doctors/passwords_controller.rb
# frozen_string_literal: true

class Doctors::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/doctors/registrations_controller.rb
# frozen_string_literal: true

class Doctors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    if current_admin_user.nil?
      redirect_to root_path
      flash[:error] = "Access denied."
    else
      super
    end
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/doctors/unlocks_controller.rb
# frozen_string_literal: true

class Doctors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    @doctor = resource
  end

  def update_recommendation
    @appointment = Appointment.find(params[:appointment_id])
    @appointment.update(recommendation: params[:recommendation])
    flash[:success] = 'Recommendation added successfully'
    redirect_to request.referer
  end

  def recommendations
    @doctor = current_doctor
    @appointments = @doctor.appointments.includes(:user)
  end
  private

  def collection
    Doctors.ordered
  end

  def resource
    collection.find(params[:id])
  end
end

app/views/doctors/recommendations.html.erb
<div class="container max-w-md bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700" style="width: 500px;">
  <% @appointments.each do |appointment| %>
    <ol class="list-group list-group-numbered text-center">
      <li class="list-group-item">
        <div class="max-w-md bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
          <div class="p-6 text-center">
            <h4 class="mb-2 block font-sans text-2xl text-white font-semibold leading-snug tracking-normal text-blue-gray-900 antialiased">
            Patient: <%= appointment.user.first_name %> <%= appointment.user.last_name %>
            </h4>
            <p class="block text-sm text-gray-500 truncate dark:text-gray-400">
            <%= appointment.recommendation %>
            <% if appointment.recommendation.blank? %>
              <%= form_with(url: update_recommendation_doctor_path(current_doctor), method: :patch) do |f| %>
                <%= f.hidden_field :appointment_id, value: appointment.id %>
                <%= f.label :recommendation, class: "text-white" %>
                <%= f.text_area :recommendation, rows: 6, cols: 40 %>
                <%= f.submit "Add recommendation", class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700" %>
              <% end %>
              <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                <%= appointment.user.phone %>
              </p>
              <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                Date&Time: <%= appointment.created_at %>
              </p>
            <% end %>
            </p>
          </div>
        </div>
      </li>
    </ol>
  <% end %>
</div>