config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about_us', to: "home#about"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :doctors, controllers: { registrations: 'doctors/registrations' }
  devise_for :users
  resources :categories, only: [:index, :show]
  resources :appointments, only: [:new, :create ]
  resources :users, only: [:profile] do
    get 'appointments', to: 'users#appointments', on: :member
  end
  resources :doctors, only: [:index, :show] do
    get 'recommendations', on: :member
    patch 'update_recommendation', on: :member
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :doctors, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  scope :ordered, -> { order(:name) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = resource
  end

  private

  def collection
    Category.ordered
  end

  def resource
    collection.find(params[:id])
  end
end

app/views/categories/show.html.erb
<div class="max-w-md bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
  <% @category.doctors.each do |doctor| %>
    <%= image_tag doctor.category.name, class: "rounded-t-lg" %>
    <div class="p-5 text-center">
      <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= doctor.first_name %> <%= doctor.last_name %></h5>
      <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= doctor.category.name %></p>
      <% if user_signed_in? %>
        <%= form_tag appointments_path, method: :post do %>
          <%= hidden_field_tag :doctor_id, doctor.id %>
          <%= hidden_field_tag :user_id, current_user.id %>
          <% if doctor.appointments.opened.count >= Doctor::MAX_APPOINTMENT_COUNT %>
            <%= button_to 'Busy schedule', '#', disabled: true, class: 'disabled-button text-white' %>
            <% else %>
            <%= submit_tag 'Make an appointment', class: "text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>