config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'about_us', to: "home#about"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :doctors, controllers: { registrations: 'doctors/registrations' }
  devise_for :users
  resources :categories, only: [:index, :show]
  resources :appointments, only: [:new, :create ]
  resources :users, only: [:profile] do
    get 'appointments', to: 'users#appointments', on: :member
  end
  resources :doctors, only: [:index, :show] do
    get 'recommendations', on: :member
    patch 'update_recommendation', on: :member
  end
end

app/views/layouts/_aside.html.erb
<button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="aside-toggle-button inline-flex items-center p-2 mt-2 ml-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
   <span class="sr-only">Toggle sidebar</span>
   <svg class="w-6 h-6 toggle-icon" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path class="open-icon" clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
      <path class="close-icon hidden" clip-rule="evenodd" fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z"></path>
   </svg>
</button>

<aside id="logo-sidebar" class="side" aria-label="Sidebar">
  <div class="sdiv">
    <%= image_tag "logo_polyclinic" %>
    <% if user_signed_in? || doctor_signed_in? %>
      <div class="flex flex-col items-center">
        <% if user_signed_in? %>
          <h4 class="sh4">Patient of Polyclinic</h4>
          <h4 class="sh4"><%= current_user.first_name %> <%= current_user.last_name %></h4>
          <p class="sp"><%= current_user.email %></p>
        <% elsif doctor_signed_in? %>
          <h4 class="sh4">Doctor of Polyclinic</h4>
          <h4 class="sh4"><%= current_doctor.first_name %> <%= current_doctor.last_name %></h4>
          <p class="sp"><%= current_doctor.phone %></p>
        <% end %>
        <%= button_to destroy_user_session_path, method: :delete, form: { turbolink: false } do %>
          <svg aria-hidden="true" class="logo-exit" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd"></path></svg>
        <% end %>
      </div>
    <% else %>
      <div class="text-center">
        <%= link_to new_user_session_path do %>
          <button type="button" class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 shadow-lg shadow-blue-500/50 dark:shadow-lg dark:shadow-blue-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Log in</button>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <button type="button" class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 shadow-lg shadow-red-500/50 dark:shadow-lg dark:shadow-red-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">Sign up</button>
        <% end %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-error text-white">
        <%= flash[:error] %>
      </div>
    <% end %>
    <ul class="space-y-2 font-medium">
      <li>
      <a href="#"id="dropdownDefaultButton" class="slink" data-dropdown-toggle="dropdownHover" data-dropdown-trigger="hover" type="button">
      <svg aria-hidden="true" class="ssvg" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
      <span class="sspan">Doctors</span>
      </a>
      <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownHoverButton">
          <% @categories.each do |category| %>
            <li>
              <%= link_to category_path(category), class: "slink" do %>
                <span class="sspan"><%= category.name %> </span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>
      <% if doctor_signed_in? %>
        <li>
          <%= link_to recommendations_doctor_path(current_doctor.id), class: "slink" do %>
            <svg aria-hidden="true" class="ssvg" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
            <span class="sspan">Recommendations</span>
          <% end %>
        </li>
      <% elsif user_signed_in? %>
        <li>
          <%= link_to appointments_user_path(id: current_user.id), class: "slink" do %>
          <svg aria-hidden="true" class="ssvg" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
          <span class="sspan">Appointments</span>
          <% end %>
        </li>
      <% end %>
        <li>
          <%= link_to about_us_path, class: "slink" do %>
            <svg aria-hidden="true" class="ssvg" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path><path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path></svg>
            <span class="sspan">About us</span>
          <% end %>
        </li>
    </ul>
    <p class="font-bold text-center lime"><%= notice %></p>
    <p class="font-bold text-center lime"><%= alert %></p>
    <% if flash[:success] %>
      <div class="px-4 py-3 text-white rounded-lg bg-lime" role="alert">
        <p class="font-bold text-center"><%= flash[:success] %></p>
      </div>
    <% end %>
  </div>
</aside>
<script>
  const dropdownButton = document.getElementById('dropdownDefaultButton');
  const dropdown = document.getElementById('dropdown');

  function toggleDropdown() {
    dropdown.classList.toggle('hidden');
  }

  dropdownButton.addEventListener('click', toggleDropdown);

  window.addEventListener('click', function(event) {
    if (!dropdown.contains(event.target) && !dropdownButton.contains(event.target)) {
      dropdown.classList.add('hidden');
    }
  });

  const button = document.querySelector('[data-drawer-toggle="logo-sidebar"]');
  const sidebar = document.getElementById('logo-sidebar');
  const toggleIcon = button.querySelector('.toggle-icon');
  const openIcon = button.querySelector('.open-icon');
  const closeIcon = button.querySelector('.close-icon');

  button.addEventListener('click', () => {
    sidebar.classList.toggle('-translate-x-full');
    toggleIcon.classList.toggle('open-icon');
    toggleIcon.classList.toggle('close-icon');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polyclinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= favicon_link_tag "favicon" %>
  </head>

  <body>
    <%= render "layouts/aside" %>
    <main class="p-4 sm:ml-64 flex items-center justify-center h-screen">
      <%= yield %>
    </main>
  </body>
</html>